name: Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # Runs at 09:00 UTC (17:00 Taipei Time)
  push:
     branches:
       - main
jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync raw_companyinfo.csv
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.REPO_FILE_SYNC_WENCHIEHLEE_INVESTMENT }}
          CONFIG_PATH: .github/sync.yml
          COMMIT_EACH_FILE: false
          PR_LABELS: "automated-sync"
          SKIP_PR: true
